Feature/optimizations
Rikj000/MoniGoMani pull request #106
Opened 2021-08-16 14:40 UTC by topscoder

Ehmmmm ... 🙉

* Introducing a new interactive installer to download & install Freqtrade (optional) and MoniGoMani HyperStrategy (optional)
* Refactored the logging functionality to log to file/stdout
* Rewrote most shell commands to use Python implementations for better cross OS compatibility
* Refactored `mgm-hurry`. Results in SoC -> more cleaner modules in `user_data/mgm_tools/mgm_hurry`
* Added unit tests for each of these modules
* Implemented mock objects for more pure unit testing
* Loads of polishing, cleaning, fixing
* Development: Implemented `pipenv` to run all commands in a clean and enclosed environment
* Development: Implemented `pre-commit` to run all checks and tests prior to committing code
* Development: GitHub Actions now always run: 
*  - Code Analysis *pylint flake8*
*  - Unit Tests *pytest*

.... 🙉

2021-08-16 22:56 UTC, Rikj000 requested changes
Thank you so much for this PR! Can't wait to merge it all in! :smile: 

However there are still some minor remarks that should be applied +
I'd like to test this PR thoroughly myself before merging it into `development` :slightly_smiling_face:

2021-08-16 22:56 UTC, Rikj000 commented on mgm-hurry
> +                self._logger.info(
Refactor to single line

2021-08-16 22:56 UTC, Rikj000 commented on mgm-hurry
> -        if os.path.exists(strategy_config_hyperopt_path):
This check should not be removed!
Other strategies create a `StrategyName.json` file after HyperOpting and it must be possible to clear these with `mgm-hurry cleanup`

2021-08-16 23:01 UTC, Rikj000 commented on user_data/mgm_tools/mgm_hurry/MoniGoManiLogger.py
> +# --- ↑↓ Do not remove these libs ↑↓ -----------------------------------------------------------------------------------
:heavy_check_mark: Done

2021-08-16 23:06 UTC, Rikj000 commented on user_data/mgm_tools/mgm_hurry/FreqtradeCli.py
> +        if self.install_type is None:
:heavy_check_mark: Done

2021-08-16 23:10 UTC, Rikj000 commented on mgm-hurry
> +                self._logger.info(
:heavy_check_mark: Done

2021-08-16 23:12 UTC, Rikj000 commented on user_data/mgm_tools/mgm_hurry/MoniGoManiCli.py
> +            repo = Repo.clone_from(GIT_URL_MONIGOMANI,
:heavy_check_mark: Done

2021-08-16 23:15 UTC, Rikj000 commented on installer.sh
> +MGM_REPO_URL="https://github.com/topscoder/MoniGoMani.git"
We'll hold off with changing this until right before merging to maintain easy test-ability.

2021-08-16 23:18 UTC, Rikj000 commented on user_data/mgm_tools/mgm_hurry/MoniGoManiConfig.py
> +                        'loss': 'WinRatioAndProfitRatioLoss',
:heavy_check_mark: Done

2021-08-16 23:21 UTC, Rikj000 commented on user_data/mgm_tools/mgm_hurry/FreqtradeCli.py
> +                'FreqtradeCli::installation_exists() succeeded because install_type is set to docker.',
:heavy_check_mark: Done

2021-08-16 23:28 UTC, Rikj000 commented on user_data/mgm_tools/mgm_hurry/FreqtradeCli.py
> +                'FreqtradeCli::installation_exists() succeeded because install_type is set to docker.',
:heavy_check_mark: Done

2021-08-16 23:31 UTC, Rikj000 requested changes
Review updated, already checked off half of the remarks!
But now I should hit the sack.. :sweat_smile:
Tomorrow there's another day :relaxed:

2021-08-17 05:22 UTC, topscoder commented on .pylintrc
> +indent-string='  '
Should be 4 indeed. Fixed in #89d23d4cf326003b7b345e405ca08c70362c02ec

2021-08-17 05:26 UTC, topscoder commented on Pipfile
> +[dev-packages]
True. Added `isort` as dependency (+ sorted the packages list already) :)
#0881c2255c0bec34489e52ad2ecba089a797c17c

2021-08-17 05:29 UTC, topscoder commented on docker-compose.yml
>  version: '3'
True. Reverted back to your last version #aa4fb5a6a42d543832b9055e619bfcec1ae2ea6b

2021-08-17 05:29 UTC, topscoder commented on installer.sh
> +MGM_REPO_URL="https://github.com/topscoder/MoniGoMani.git"
Correct, that's the purpose.

2021-08-17 05:38 UTC, topscoder commented on mgm-hurry
> -        if os.path.exists(strategy_config_hyperopt_path):
Referenced #107 to discuss and fix.

2021-08-17 06:51 UTC, topscoder commented on mgm-hurry
> -        if os.path.exists(strategy_config_hyperopt_path):
Fixed by #5eb4c8245554c613876f0a129fed8cc9e1e55091

2021-08-17 06:54 UTC, topscoder commented on Documentation/Docs-MGM-Hurry.md
>  MGM-Hurry is a command line tool to speedup & simplify the setup & usage of [Freqtrade](https://www.freqtrade.io/en/stable/) in combination with the [MoniGoMani](https://github.com/Rikj000/MoniGoMani
Fixed in 5eb4c8245554c613876f0a129fed8cc9e1e55091

2021-08-17 06:57 UTC, topscoder commented on mgm-hurry
> +                self._logger.info(
Closed by 5eb4c8245554c613876f0a129fed8cc9e1e55091

2021-08-17 20:07 UTC, Rikj000 commented on .pylintrc
> +indent-string='  '
:heavy_check_mark: Done

2021-08-17 20:26 UTC, Rikj000 commented on Documentation/Docs-MGM-Hurry.md
>  MGM-Hurry is a command line tool to speedup & simplify the setup & usage of [Freqtrade](https://www.freqtrade.io/en/stable/) in combination with the [MoniGoMani](https://github.com/Rikj000/MoniGoMani
:heavy_check_mark: Done

2021-08-17 20:26 UTC, Rikj000 commented on Pipfile
> +[dev-packages]
:heavy_check_mark: Done

2021-08-17 20:26 UTC, Rikj000 commented on docker-compose.yml
>  version: '3'
:heavy_check_mark: Done

2021-08-17 20:30 UTC, Rikj000 commented on user_data/mgm-config.json
> +{
:heavy_check_mark: Done

2021-08-17 20:30 UTC, Rikj000 commented on .vscode/launch.json
> +{
:heavy_check_mark: Done

2021-08-17 20:31 UTC, Rikj000 commented on .vscode/settings.json
>  {
:heavy_check_mark: Done

2021-08-17 20:32 UTC, Rikj000 commented on mgm-hurry
> -        if os.path.exists(strategy_config_hyperopt_path):
:heavy_check_mark: Done

2021-08-17 20:38 UTC, Rikj000 commented on installer.sh
> +MGM_REPO_URL="https://github.com/topscoder/MoniGoMani.git"
Apart from this one I believe all remarks are implemented by now! :partying_face: 
Aka, time to start testing locally :smile:

2021-08-17 20:58 UTC, Rikj000 commented on installer.sh
> +pipenv install -r https://github.com/topscoder/MoniGoMani/blob/feature/optimizations/Pipfile
Throws following error when `pipenv` is not in `$PATH`:
`installer.sh - line 326: pipenv: command not found`

However when I change the command to `python3 -m pipenv install -r https://...`,
then I'm greeted with another error:
![pipenv-error](https://user-images.githubusercontent.com/24852597/129799553-f4dc97f1-d9ea-4632-83b1-e184141803e2.png)

2021-08-17 21:02 UTC, Rikj000 commented on user_data/mgm_tools/mgm_hurry/FreqtradeCli.py
> +from git import Repo
No `git` module is found when running `python3 ./mgm-hurry up`:
![no-git-module-error](https://user-images.githubusercontent.com/24852597/129800146-dddcb3f5-166b-41b2-9490-cfee52e8a663.png)

2021-08-17 21:04 UTC, Rikj000 reviewed
**Review update:**
Tested the `installer.sh` & `mgm-hurry up`, sadly both still appear to be having issues.
I'll do the rest of my testing after these 2 bugs have been resolved.

2021-08-18 08:20 UTC, topscoder commented on user_data/mgm_tools/mgm_hurry/FreqtradeCli.py
> +from git import Repo
That's an environment issue because pipenv installed all modules in it's isolated environment (which is supposed to be).

Fixed now by proposing `pipenv run python3 ./mgm-hurry up` at the end of the installer.sh routine.

Note: `pipenv run ./mgm-hurry up` will in most cases also run fine, but adding python3 is probably more robust.

2021-08-18 08:22 UTC, topscoder commented on installer.sh
> +pipenv install -r https://github.com/topscoder/MoniGoMani/blob/feature/optimizations/Pipfile
Made this procedure a lot more robust. Already pushed.

2021-08-19 19:33 UTC, Rikj000 commented on installer.sh
> +pipenv install -r https://github.com/topscoder/MoniGoMani/blob/feature/optimizations/Pipfile
:heavy_check_mark: Done

2021-08-19 19:34 UTC, Rikj000 commented on user_data/mgm_tools/mgm_hurry/FreqtradeCli.py
> +from git import Repo
:heavy_check_mark: Done

2021-08-19 19:37 UTC, Rikj000 reviewed
**Review Update:**
@topscoder it's looking all good to me now mate, amazing work truly! :partying_face: 
Just finished up a flawless install & it was a breeze to go through which made me smile with a HyperOpting machine at the end of it! :heart_eyes:

If you agree then I think we can finally merge it in! :tada:

2021-08-20 20:45 UTC, Rikj000 commented on installer.sh
> +MGM_REPO_URL="https://github.com/topscoder/MoniGoMani.git"
:heavy_check_mark: Last one, done!! :partying_face:

2021-08-20 20:49 UTC, Rikj000 approved these changes
Looking good to me! :smile: Let's finally merge into `development`! :tada:

2021-08-20 20:51 UTC, merged