✨ Allow config difference core trend timeframe
Rikj000/MoniGoMani pull request #156
Opened 2021-10-10 12:36 UTC by taina0407

- Add new 'trend_timeframe' in mgm-config.json to setting timeframe to detect core trend, if not set then using default timeframe

# TODO: 
- Didn't found any documentation about HT_TRENDMODE required startup candles number, so currently setting it to 200. This should to optimize incase of using long core trend timeframe like 1d might cause the bot loading candle pretty slow
- Using better logic to merge core_trend column to informative and main dataframe, because I'm quite new on python so don't know a good way to implement it yet, currently using manual rename and delete

2021-10-11 22:03 UTC, Rikj000 requested changes
Did some improvements to the code already as I was setting up a development environment for this PR.
I'll get to more thorough debugging of the code soon & will see if all checks out and if I can find a way to do this with a bit less code duplication.

@taina0407 already thank you for this PR! :pray:
Feel free to also try to find a solution for this with less code duplication :slightly_smiling_face:

2021-10-11 22:03 UTC, Rikj000 commented on user_data/strategies/MasterMoniGoManiHyperStrategy.py
> +                                       startup_candles=self.startup_candle_count,
For now I think it's fine to set the `startup_candle_count` to the one defined in `mgm-config`

2021-10-11 22:03 UTC, Rikj000 commented on user_data/strategies/MasterMoniGoManiHyperStrategy.py
> +            informative['ht_trendmode'] = informative[f'ht_trendmode_{self.core_trend_timeframe}']
Indeed, there must be a cleaner way to do this :slightly_smiling_face:

2021-10-12 09:01 UTC, taina0407 commented on user_data/strategies/MasterMoniGoManiHyperStrategy.py
> +            informative['ht_trendmode'] = informative[f'ht_trendmode_{self.core_trend_timeframe}']
Updated rename logic using panda rename.
Also tried to debug using PyCharm and verified that the core trend is set correctly in both backtest and dryrun mode 🥰

2021-10-13 16:57 UTC, Rikj000 approved these changes
Also tested with PyCharms debugger and the implementation looks good to me! :smile: 

I took the liberty of also removing some double/unused dataframe columns which I noticed during my debugging, this should result in less memory usage & perhaps a faster HyperOpt too :slightly_smiling_face:

However I still need to thoroughly test both of our changes now before I get to merging.
Feel free to already append some test results:
- From before the PR implementation as comparison
- Some of the best results yielded with the new feature implemented

So we can be sure & document it in this PR that it does indeed bring improvements

2021-10-14 15:52 UTC, Rikj000 commented
With the timeframes configured as following I was already able to yield better results on one of my first tests:
```json
{
    "timeframe": "30m",
    "trend_timeframe": "4h",
    "backtest_timeframe": "5m"
}
```
![core-trend-4h](https://user-images.githubusercontent.com/24852597/137352610-a3c81e38-96f5-449e-b415-471c59f3feec.png)

2021-10-15 21:35 UTC, Rikj000 commented
@taina0407 `1d` didn't appear to yield me better results, so I guess I'll make the default `4h`.
Then it's up to users to test & improve further upon this settings :slightly_smiling_face: 
```json
{
    "timeframe": "30m",
    "trend_timeframe": "1d",
    "backtest_timeframe": "5m"
}
```
![1d-core-trend](https://user-images.githubusercontent.com/24852597/137556103-0804c658-837d-4d08-9b56-dd924a16fa0f.png)
However as discussed in PMs the implementation of this setting likely will still change a bit with the implementation of [issue 44](https://github.com/Rikj000/MoniGoMani/issues/44)

2021-10-15 21:41 UTC, merged